services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nxiiio/innovatech-backend:latest
    container_name: innovatech-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "10.0.151.253"
      DB_PORT: "3306"
      DB_NAME: "innovatech"
      DB_USER: "usuario"
      DB_PASSWORD: "password"
